name: Purge jsDelivr

on:
  push:
    branches: [main]

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache
        run: |
          curl -s -X GET "https://purge.jsdelivr.net/gh/broadway23/exit-intent-popup/exit-popup.js"
